name: Toolbelt
description: Deploy patched VTEX toolbelt, cache for faster deployment, and do login.
author: VTEX

inputs:
  account:
    description: 'Account to use on login'
    required: true
  appKey:
    description: 'VTEX App Key to login'
    required: true
  appToken:
    description: 'VTEX App Token to login'
    required: true
  workspace:
    description: 'Workspace to start after login, default master'
    required: false
    default: master
  git:
    description: 'Source repository to clone (org/repo)'
    required: false
    default: vtex/toolbelt
  branch:
    description: 'Which branch to use on git'
    required: false
    default: master

runs:
  using: 'composite'
  steps:

    - name: Checkout VTEX Toolbelt
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.git }}
        ref: ${{ inputs.branch }}
        path: toolbelt

    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
        cache-dependency-path: toolbelt/yarn.lock
      continue-on-error: true

    - name: Cache VTEX Toolbelt
      id: cache-toolbelt
      uses: actions/cache@v3
      with:
        path: |
          toolbelt
          /usr/local/bin/vtex-e2e
        key: ${{ runner.os }}-${{ inputs.git }}-${{ inputs.branch }}


    - name: Install VTEX Toolbelt
      if: steps.cache-toolbelt.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile
        yarn build
        cp bin/run bin/vtex-e2e
        ln -s $(pwd)/bin/vtex-e2e /usr/local/bin/
        vtex-e2e whoami || echo "First call to warm it up"
        VERSION=$(vtex-e2e version)
        echo ::notice title=VTEX Toolbelt version::$VERSION
      working-directory: toolbelt
      shell: bash

    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: login
      shell: bash
      env:
        IN_CYPRESS: 'true'
        VTEX_ACCOUNT: ${{ inputs.account }}
        VTEX_APP_KEY: ${{ inputs.appKey }}
        VTEX_APP_TOKEN: ${{ inputs.appToken }}
        VTEX_WORKSPACE: ${{ inputs.workspace }}
        VTEX_TOOLBELT_GIT: ${{ inputs.git }}
        VTEX_TOOLBELT_BRANCH: ${{ inputs.branch }}

branding:
  icon: activity
  color: yellow
