name: VTEX Toolbelt Action
description: Deploy patched VTEX toolbelt, cache for faster deployment, and do login.
author: VTEX

inputs:
  authenticate:
    description: 'Do authentication after deploy'
    required: false
    default: 'true'
  account:
    description: 'Account to use on login'
    required: false
  appKey:
    description: 'VTEX App Key to login'
    required: false
  appToken:
    description: 'VTEX App Token to login'
    required: false
  workspace:
    description: 'Workspace to start after login, default master'
    required: false
    default: master
  version:
    description: 'Version of VTEX Toolbelt to be installed'
    required: false
    default: 3.0.0-beta-ci.0

runs:
  using: 'composite'
  steps:
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get yarn cache path
      id: cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
    - name: Cache VTEX Toolbelt
      id: cache-toolbelt
      uses: actions/cache@v3
      with:
        path: ${{ steps.cache-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-yarn   
    - name: Install VTEX Toolbelt
      # if: steps.cache-toolbelt.outputs.cache-hit != 'true'
      run: |
        yarn global add vtex@${{ inputs.version }}
        VERSION=$(vtex version)
        echo ::notice title=VTEX Toolbelt version::$VERSION
      shell: bash
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      env:
        VTEX_ACCOUNT: ${{ inputs.account }}
        VTEX_APP_KEY: ${{ inputs.appKey }}
        VTEX_APP_TOKEN: ${{ inputs.appToken }}
        VTEX_AUTHENTICATE: ${{ inputs.authenticate }}
        VTEX_WORKSPACE: ${{ inputs.workspace }}
      shell: bash

branding:
  icon: terminal
  color: red
